name: Gsi Bot
 
on:  workflow_dispatch

env:
  TYPE: build
  TZ: Asia/Manila
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 505600

    steps:
       - name: Initial setup
         uses: actions/checkout@master
     # Cleanup The Actions Workspace Using Custom Composite Run Actions
     #  - uses: rokibhasansagar/slimhub_actions@main

         
       - name: Setup env
         continue-on-error: true
         timeout-minutes: 100
         run: |
               
